---
services:
  - name: registry.service
    uri: https://raw.githubusercontent.com/Financial-Times/coco-docker-image-cache-services/master/service-files/registry.service
  - name: elb-presence.service
    uri: https://raw.githubusercontent.com/Financial-Times/coco-docker-image-cache-services/master/service-files/elb-presence.service
  - name: splunk-forwarder.service
    uri: https://raw.githubusercontent.com/Financial-Times/fleet/master/service-files/splunk-forwarder.service
  - name: registry-proxy.service
    uri: https://raw.githubusercontent.com/Financial-Times/up-registry-proxy/master/registry-proxy.service
  - name: system-healthcheck.service
    uri: https://raw.githubusercontent.com/Financial-Times/fleet/master/service-files/system-healthcheck.service
  - name: system-healthcheck-sidekick.service
    uri: https://raw.githubusercontent.com/Financial-Times/fleet/master/service-files/system-healthcheck-sidekick.service
  - name: fleet-unit-healthcheck.service
    uri: https://raw.githubusercontent.com/Financial-Times/fleet/master/service-files/fleet-unit-healthcheck.service
    version: v4
  - name: fleet-unit-healthcheck-sidekick.service
    uri: https://raw.githubusercontent.com/Financial-Times/fleet/master/service-files/fleet-unit-healthcheck-sidekick.service
  - name: aggregate-healthcheck@.service
    uri: https://raw.githubusercontent.com/Financial-Times/fleet/master/service-files/aggregate-healthcheck@.service
    version: v42
    count: 1
  - name: aggregate-healthcheck-sidekick@.service
    uri: https://raw.githubusercontent.com/Financial-Times/fleet/master/service-files/aggregate-healthcheck-sidekick@.service
    count: 1

