---
services:
  - name: registry.service
  - name: elb-presence@.service
    uri: https://raw.githubusercontent.com/Financial-Times/up-service-files/master/elb-presence@.service
    count: 1
  - name: splunk-forwarder.service
    uri: https://raw.githubusercontent.com/Financial-Times/fleet/master/splunk-forwarder.service
  - name: system-healthcheck.service
    uri: https://raw.githubusercontent.com/Financial-Times/fleet/master/system-healthcheck.service
  - name: system-healthcheck-sidekick.service
    uri: https://raw.githubusercontent.com/Financial-Times/fleet/master/system-healthcheck-sidekick.service
  - name: fleet-unit-healthcheck.service
    uri: https://raw.githubusercontent.com/Financial-Times/fleet/master/fleet-unit-healthcheck.service
  - name: fleet-unit-healthcheck-sidekick.service
    uri: https://raw.githubusercontent.com/Financial-Times/fleet/master/fleet-unit-healthcheck-sidekick.service
  - name: aggregate-healthcheck@.service
    uri: https://raw.githubusercontent.com/Financial-Times/up-service-files/master/aggregate-healthcheck@.service
    count: 1
  - name: aggregate-healthcheck-sidekick@.service
    uri: https://raw.githubusercontent.com/Financial-Times/up-service-files/master/aggregate-healthcheck-sidekick@.service
    count: 1
  - name: vulcan.service
    uri: https://raw.githubusercontent.com/Financial-Times/fleet/master/vulcan.service
  - name: image-cleaner.service
    uri: https://raw.githubusercontent.com/Financial-Times/fleet/master/image-cleaner.service
